[tool.poetry]
name = "goldfinch10.ru"
version = "0.1.0"
description = "site-portfolio"
authors = ["Igor Radionov <uncle_lonli@outlook.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
